Several changes in "wp-source" API
frontity/frontity pull request #112
Opened 2019-05-31 14:53 UTC by DAreRodz

Closes #65, #79, #82.
Fixes #102.

2019-05-31 14:55 UTC, luisherranz commented
👏👏👏

2019-05-31 15:27 UTC, luisherranz requested changes
Wow!! Amazing work @DAreRodz!! 👏👏

I just have this comment about the public API of routeUtils:
We have a lot of functions and even the React `<Link>` components with a `routeOrParams` argument, so instead of `routeToParams` and `paramsToRoute` what do you think about a `getParams` and `getRoute` that accept a `routeOrParams`? Or maybe maintain `routeToParams` and `paramsToRoute` but add the other two.

And I'll take a look at the error of `deepMerge` myself.

2019-05-31 15:27 UTC, luisherranz commented on packages/wp-source/src/actions.ts
> +    if (typeof routeOrParams === "string") {
I would get rid of all this and I'd use only something like:
```js
const { path, page } = getParams(routeOrParams);
```

2019-05-31 15:27 UTC, luisherranz commented on packages/wp-source/src/actions.ts
> +    if (typeof routeOrParams === "string") {
Same here in router:
https://github.com/frontity/frontity/blob/dev/packages/tiny-router/src/actions.ts#L12-L17

```js 
const { path, page } = libraries.source.getParams(routeOrParams);
```

2019-05-31 15:27 UTC, luisherranz commented on packages/wp-source/src/index.ts
> +      routeUtils
For easy access I'd spread `...routeUtils` to get:
`libraries.source.routeToParams` vs `libraries.source.routeUtils.routeToParams`.

2019-05-31 15:27 UTC, luisherranz commented on packages/wp-source/src/state.ts
> +  get: ({ state }) => routeOrObj => {
I really like to have a `normalize` util but here I'd try to get rid of the ifs delegating that to the utils, doing something like:
```js
const route = getRoute(routeOrParams);
return state.source.data[route] || {};
```

2019-06-03 09:39 UTC, luisherranz commented
@DAreRodz tell me the steps to reproduce the error you saw with `deepmerge` please.

2019-06-03 09:41 UTC, DAreRodz commented
In this branch:

- go to `/examples/mars-theme-example`

2019-06-03 10:02 UTC, DAreRodz commented
Never mind that, I forgot to do `npm i`. Just a missing dependency. 🙄

2019-06-03 10:10 UTC, luisherranz commented
No prob!

2019-06-04 11:11 UTC, luisherranz commented
I've fixed the bug of `<List>` and it's now included in this PR.

2019-06-04 11:33 UTC, DAreRodz commented
@luisherranz, @orballo,  ready for review again!

2019-06-04 14:53 UTC, luisherranz approved these changes
Incredible work @DAreRodz!

We're almost ready for the release candidate 🎉 🎉

2019-06-04 14:53 UTC, merged