fix(image): add height prop and set loading=auto if no height is present
frontity/frontity pull request #207
Opened 2019-09-18 17:30 UTC by DAreRodz

#### Description of what you did:

- Add a `height` prop to the `Image` component.
- Set the `loading` prop to `auto` if the`height` property is not set, avoiding Chrome to lazy-load the image.

Fixes #194.

#### My PR is a:

- 🐞 Bug fix
- 🚀 New feature
- 🔝 Improvement

#### Is the PR ready to be merged?

- ✅ Yes!
- 🚧 Work in progress

2019-09-18 17:45 UTC, luisherranz commented
> #### My PR is a:
> * 🐞 Bug fix
> * 🚀 New feature
> * 🔝 Improvement
> 
> #### Is the PR ready to be merged?
> * ✅ Yes!
> * 🚧 Work in progress

Isn't it clear that you should remove the non-relevant ones? And leave it like this? 😓 

> #### My PR is a:
> * 🐞 Bug fix
> 
> #### Is the PR ready to be merged?
> * ✅ Yes!

2019-09-18 17:46 UTC, luisherranz commented
I removed the checkboxes because GitHub thinks it's progress:
<img width="557" alt="Screen Shot 2019-09-18 at 19 45 52" src="https://user-images.githubusercontent.com/3305402/65172318-fa1bb400-da4c-11e9-8067-a22339a600aa.png">

2019-09-19 09:03 UTC, luisherranz commented
It'd be amazing to take this opportunity to add e2e tests for the image component.

2019-09-19 14:06 UTC, DAreRodz commented
Yeah, I'm working on that.

2019-09-20 09:29 UTC, luisherranz commented
Let me know once this is ready.

2019-09-20 10:00 UTC, luisherranz requested changes

2019-09-20 10:00 UTC, luisherranz commented on e2e/packages/image/src/index.tsx
> +  src: "https://test.frontity.io/wp-content/uploads/2016/11/Gullfoss.jpg",
Could you please use a local images? I don't want this test to fail if test.frontity.io is offline or if those images are removed. You can download them and add them to the `"image"` package.

2019-09-25 07:31 UTC, luisherranz commented
I love the `useInView` e2e tests! Good work 👏

2019-10-01 16:21 UTC, DAreRodz commented
@luisherranz, can you check again this PR?

2019-10-02 10:15 UTC, luisherranz approved these changes
Approved!

2019-10-02 10:16 UTC, merged