Add Menu Toggle to Mars Theme
frontity/frontity pull request #233
Opened 2019-11-05 10:48 UTC by segunadebayo

#### Description of what you did:
Add a Menu Toggle button to the Mars Theme. Here's what I plan to do:
1. Create a simple modal implementation to house the menu links.
2. On mobile, hide the menu links in Header and show only the toggle button
3. On Click of the Menu Button, show the modal with links

#### My PR is a:
- 🔝 Improvement

#### Is the PR ready to be merged?
- 🚧 Work in progress

2019-11-06 18:43 UTC, luisherranz requested changes
Awesome work!

I think the code is ready for merge.

Two things: 
- If you don't need the `use-local-storage` and `use-media-queries` for this, I'd remove the files to avoid confusion.
- Same for `afterCSR`.

I know you're going to add them again for other things, but for now I'd leave them out to keep things clean.

2019-11-07 09:42 UTC, segunadebayo commented
Thanks for the feedback, Luis. I'll make the changes as requested

2019-11-07 19:26 UTC, luisherranz approved these changes

2019-11-07 19:29 UTC, luisherranz commented
Perfect now. Thanks @segunadebayo.

2019-11-07 19:29 UTC, merged