CLI: Add theme param to create
frontity/frontity pull request #288
Opened 2020-01-24 21:48 UTC by michalczaplinski

#### Description of what you did:

This PR adds the ability to pick a theme when running the `frontity create`.

#### My PR is a:

- 🚀 New feature

#### Is the PR ready to be merged?

- 🚧 Work in progress

2020-01-27 19:19 UTC, DAreRodz requested changes
Hey Michal!

There is a problem with the `create` command. When you select a different theme than `mars-theme` the `frontity.settings.js` file won't include the theme you choose but `mars`. It's the [`createFrontitySettings`](https://github.com/frontity/frontity/blob/add-theme-picker/packages/frontity/src/steps/index.ts#L118L172) function (that is being called [here](https://github.com/frontity/frontity/blob/add-theme-picker/packages/frontity/src/commands/create.ts#L58)). Could you change that function and add some tests?

Code looks fine, by the way. 😊

2020-01-27 20:02 UTC, luisherranz commented
I've been thinking about this during the last few days and I think we can solve it using the `frontity.config.js` file: https://community.frontity.org/t/defining-default-settings-for-frontity-packages/1139

Please read that feature topic and let me know what you think (in the topic).

2020-01-27 22:20 UTC, michalczaplinski commented
> There is a problem with the `create` command. When you select a different theme than `mars-theme` the `frontity.settings.js` file won't include the theme you choose but `mars`. It's the [`createFrontitySettings`](https://github.com/frontity/frontity/blob/add-theme-picker/packages/frontity/src/steps/index.ts#L118L172) function (that is being called [here](https://github.com/frontity/frontity/blob/add-theme-picker/packages/frontity/src/commands/create.ts#L58)). 

oh, nice catch @DAreRodz, thanks! 🙂

2020-01-28 18:36 UTC, luisherranz commented
Yeah, that is actually the bug!
https://github.com/frontity/frontity/issues/132

Sorry we forgot to add it to the sprint. I've done so now and added a `Fixes` to this PR.

2020-01-29 14:19 UTC, DAreRodz approved these changes
Looks good to me! 👌

2020-01-29 14:20 UTC, DAreRodz commented
PS: I guess the default settings feature would be implemented in another PR. This is totally fine, isn't it?

2020-01-29 14:41 UTC, luisherranz approved these changes
Great work @michalczaplinski!

2020-01-29 14:55 UTC, merged

2020-01-29 16:32 UTC, luisherranz commented
> PS: I guess the default settings feature would be implemented in another PR. This is totally fine, isn't it?

Yeah, I guess this is fine for now. 

For reference, this should be the next step: https://community.frontity.org/t/defining-default-settings-for-frontity-packages/1139/3