Add CLI env variables for `dev`, `build` and `serve` commands
frontity/frontity pull request #458
Opened 2020-06-03 10:05 UTC by DAreRodz

**What**:

Add these env variables to the `dev`, `build` and `serve` commands:
- target: `FRONTITY_TARGET`
- port: `FRONTITY_PORT`
- https: `FRONTITY_HTTPS`
- production: `FRONTITY_PRODUCTION`
- development: `FRONTITY_DEVELOPMENT`
- publicPath: `FRONTITY_PUBLIC_PATH`
- dontOpenBrowser: `FRONTITY_DONT_OPEN_BROWSER`

Closes #394 

**Why**:

To allow users to pass CLI options through env variables.

**How**:

Following the implementation proposal in [Change publicPath](https://community.frontity.org/t/change-publicpath/1461/5).

**Tasks**:

- [x] Code
- [ ] TSDocs
- [ ] Unit tests
- [ ] Community discussions
- [ ] Changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)
- [ ] Link to PR in [Documentation](https://github.com/frontity/gitbook-docs/)

**Unrelated Tasks**

- TypeScript
- End to end tests
- TypeScript tests
- Update starter themes
- Update other packages

2020-06-04 10:45 UTC, luisherranz commented
@luisherranz test

2020-06-04 12:40 UTC, DAreRodz commented
By the way, Codecov is failing because, after adding unit tests for `dev`, `build` and `serve` commands, it started to track files that were not tracked before, thus causing the coverage ratio to drop.

I tried to fix that writing some missing unit tests for other parts of the code but it wasn't enough, and I think that work if out of the scope of this PR, so I would merge this at it is.

@michalczaplinski, do you know what would happen with the coverage ratio if we merge this? Would it be reset to the score that this PR is getting?

2020-06-04 12:46 UTC, DAreRodz commented
@juanmaguitar, there is no TSdocs in this case.

You would have to create a new section for each command called **Environment variables** or something like that, or add them to their respective argument.

Whatever you think is better. :+1:

2020-06-04 16:27 UTC, michalczaplinski commented
@DAreRodz yes, I'm afraid that the codecov is going to decrease by 0.95% after merging this. 

The thing is that this does not mean that our code is less tested than before actually...

In fact, if the file was not tracked before, but is tracked now and the new test only covers 10% of the new file, the coverage is going to decrease even though we actually test MORE of the functionality.

I think we have to look into configuring jest correctly - there exist multiple additional flags for configuring coverage that for some reason are not present on the website: https://github.com/facebook/jest/blob/master/docs/Configuration.md

2020-06-05 10:02 UTC, luisherranz commented
Hey guys, I have a concern about this environment variables names clashing in the future. Could you please take a look and let me know your opinion before I continue with the review? Thanks!

https://community.frontity.org/t/change-publicpath/1461/9?u=luisherranz

2020-06-08 16:16 UTC, luisherranz commented
Unblocked based on the decision made at https://community.frontity.org/t/change-publicpath/1461/13.

2020-06-08 16:19 UTC, luisherranz requested changes
Unblocked based on the decision made at https://community.frontity.org/t/change-publicpath/1461/13.

@DAreRodz could you please implement the necessary changes?

2020-06-10 16:39 UTC, juanmaguitar approved these changes
📕 Docs PR → https://github.com/frontity/gitbook-docs/pull/93

2020-06-16 07:11 UTC, luisherranz approved these changes
Thanks @darerodz! Looks perfect to me 🙂

2020-06-16 07:11 UTC, luisherranz commented on packages/frontity/src/cli/index.ts
> +    'create bundles with "es5", "module" or "both". Default target is "both".'
Thanks for this fix 🙂

2020-06-16 11:07 UTC, merged