README md package create-frontity
frontity/frontity pull request #468
Opened 2020-06-05 09:01 UTC by juanmaguitar

**What**:

Adding README.md's of create-frontity package

**Why**:

So it has the proper info in NPM

**How**:

Creating the README.md's using on the proper folder

```
npx readme-md-generator -p ../../.github/README_TEMPLATE/package-readme.md -y
```

And then adding custom info on each README.md

**Tasks**:

**Unrelated Tasks**

- Code
- TSDocs
- TypeScript
- Unit tests
- End to end tests
- TypeScript tests
- Update starter themes
- Update other packages
- Link to PR in [Documentation](https://github.com/frontity/gitbook-docs/)
- Community discussions
- Changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Additional Comments**

2020-06-05 09:32 UTC, luisherranz requested changes

2020-06-05 09:32 UTC, luisherranz commented on .changeset/nervous-schools-teach.md
> +"create-frontity": minor
Please change this to a `patch`.

2020-06-05 09:32 UTC, luisherranz commented on .changeset/nervous-schools-teach.md
> +README.md full description
Please use proper English phrases for the changelog, ending them with a period.

2020-06-05 11:17 UTC, luisherranz requested changes

2020-06-05 11:17 UTC, luisherranz commented on packages/create-frontity/README.md
> +
This package doesn't need to be installed. It's meant to be used only in conjunction with the `npm init` command, like this:

```bash
> npm init frontity
```

2020-06-05 12:20 UTC, luisherranz approved these changes
👍

2020-06-10 01:59 UTC, merged

2020-06-10 02:00 UTC, michalczaplinski commented
Hey @juanmaguitar I've merged this one and the other remaining PRs with the READMEs.

Just as a note for the future - we have a convention that it's normally up to the PR author to merge the PR after an approval. I don't think that it's explicitly documented so you couldn't know that 🙂