Add `--analyze` flag to the `npx frontity dev` command
frontity/frontity pull request #774
Opened 2021-04-09 10:55 UTC by DAreRodz

**What**:

Add a new option to the `npx frontity dev` command to generate the HTML files for bundle analysis.

This option is `opt-in` so you would have to explicitly set `--analyze` in order to generate the HTML files.

**Why**:

This would make building times

**How**:

Adding an `--analyze` flag to the CLI's dev command and passing the value to the `dev` script of `@frontity/core`.

That value is passed down to the `plugins` function that generates the Webpack's plugin configuration. The [Bundle Analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) plugin is then added depending on the flag's value.

**Tasks**:

- [x] Code
- [x] TSDocs
- [x] TypeScript
- [x] Unit tests
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] End to end tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Update community discussions

**Additional Comments**

2021-04-09 11:02 UTC, luisherranz requested changes
Initially it looks great to me David, but could you please add it to `npx frontity build` as well? The production bundle is the one people usually analyze.

Thanks! 🙂

2021-04-09 11:06 UTC, DAreRodz commented
> could you please add it to `npx frontity build` as well? The production bundle is the one people usually analyze.

You're completely right. :sweat_smile:

Sure, it wouldn't take much time. :+1:

2021-04-09 11:31 UTC, DAreRodz commented
Done. @luisherranz, you can review it again.

2021-04-12 13:28 UTC, luisherranz approved these changes
Looks great David 🙂

I have done a slight modification to avoid deleting the `bundling` folder after the build if it was generated using `analyze: true` (https://github.com/frontity/frontity/pull/774/commits/7557a54b750e8a270922b0b2aec17284a57559d7).

Feel free to merge!

2021-04-12 13:50 UTC, luisherranz commented
Uhm, wait. I thought the `analyze` folder was inside `bundling` but it is not, sorry. I am going to revert the last commit.

2021-04-12 15:46 UTC, merged