just get the name of currentPage selected, with the mars theme
frontity/frontity pull request #881
Opened 2021-10-16 17:30 UTC by rubenlorenzo

**What**:

Keep current page selected when changing old pages. Fixes #846.

**Why**:

To know what page you are on. 

**How**:

It deletes **page/pageNumber** *to url* of the router, to compare the  url to link. So it can give a positive answer.

**Tasks**:

- [x] Code
- [ ] TSDocs
- [x] TypeScript
- [x] Unit tests
- [x] End to end tests
- [ ] TypeScript tests
- [x] Update starter themes
- [ ] Update other packages
- [ ] Update community discussions
- [ ] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

**Additional Comments**

2021-10-22 09:04 UTC, rubenlorenzo commented
Hi @luisherranz. I made this PR, but I don't know. If there is something, That I have to fix to correct by failures of the test.

2021-10-28 11:33 UTC, luisherranz requested changes

2021-10-28 11:33 UTC, luisherranz commented on packages/mars-theme/src/components/nav.js
> +      let pageNumber = state.router.link.replace(/\D/g, "");
I don't think this regular expression is safe to use. It will break if the slug contains a number. For example, `pageNumber` for `/my-category-12/page/3` would be `123` and not `3`.

You can get the page number from source data:

```js 
const data = state.source.get(state.router.link);
const pageNumber = data.page;
```

Be aware that `data.page` is always 1 for posts (not `null` or `undefined`).

2021-10-29 10:10 UTC, luisherranz commented on packages/mars-theme/src/components/nav.js
> +      let pageNumber = state.router.link.replace(/\D/g, "");
Actually, forget about `data.page`, you can use `data.route` instead, which is the link without the page.

2021-11-03 09:19 UTC, rubenlorenzo commented on packages/mars-theme/src/components/nav.js
> +      let pageNumber = state.router.link.replace(/\D/g, "");
Thank you, I will try to use it.

2021-11-07 22:07 UTC, luisherranz commented
Hey @rubenlorenzo, thanks for the changes. The code looks much nicer now 🙂

Have you tested it? Does it work?

2021-11-08 10:09 UTC, rubenlorenzo commented
Hi @luisherranz. Yes, I have tried it. It works with mars-theme-example in firefox and chrome.

2021-11-09 20:41 UTC, merged

2021-11-09 20:41 UTC, luisherranz commented
Awesome. Merged now. Thanks for your contribution @rubenlorenzo 🙂